### ISSUE TITLE
Add oneOf method

### ISSUE THREAD

**Issue by br0r** [silfverstrom/duns.js#10]
Sometimes you'll accept more than one type as argument. There needs to be a .oneOf method to accept it. It should extend the `any` object of some so it'll be able to chain format on it. 

```
Duns('5').schema(Duns.oneOf([Duns.string(), Duns.number()]).format((num) => +num)).validate().format();
```

**Comment by silfverstrom** [comment]
+1 - feels rather important. 0.1?
