### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by br0r** [silfverstrom/duns.js#13]
Documentation needs to be added for all objects. Should be done once 0.1 is complete.

**Comment by br0r** [comment]
Perhaps should start on this soon? I feel that I'm not myself aware of everything one can do. Updated docs would solve this. @silfverstrom

**Comment by br0r** [comment]
Could do it together on a hackaton, to make sure syntax is as we want it.

**Comment by silfverstrom** [comment]
Sounds good to me. I've been a bit reluctant to start this issue, probably due to laziness. Perhaps this weekend? @br0r
