### ISSUE TITLE
format method clashes with duns.date().format() 

### ISSUE THREAD

**Issue by silfverstrom** [silfverstrom/duns.js#15]
The default format method clashes with the date().format() method in the date_validator. 
Even if we made sure that only created schemas can use the format() method, the overlapping names are still causing confusion. 

My suggestion is that we rename the standard format method to something else - perhaps populate() ?

**Comment by br0r** [comment]
I agree with changing the standard format name.

My suggestions are `transform` or `returns`. I see `populate` as a something you give perhaps an ID to and it will give you back an object of data based on the argument.

**Comment by br0r** [comment]
Then again, `format` is used by moment as a way of saying "this is how I want my date returned". In the same sense as we would use it. Perhaps it would be less ambiguous to keep the format syntax and change the dateValidator.format to something like dataValidator.pattern

**Comment by silfverstrom** [comment]
I agree. +1 for date().pattern()
