### ISSUE TITLE
Syntax for assert

### ISSUE THREAD

**Issue by br0r** [silfverstrom/duns.js#36]
What is the current syntax for assert? 

If I look in the tests it's `Duns.number(100).assert;`

But in the code `assert` is a function. 

Shouldn't the syntax be `Duns.assert(value, schema);`?

**Comment by silfverstrom** [comment]
Are you perhaps referring to this line in the anyvalidator-test? 

```
(Duns.any(undefined).assert).should.throw();
```

This is a syntax-confusion with mocha/should. You give the function, without executing it, to the should-validator. It is then later on executed(this is so should can wrap it inside a try/catch block). 

Thus, the syntax for using assert in duns is, 

```
var schema = Duns.object().keys({
test : Duns.number(),
});

schema.init('100').assert(); //throws
schema.assert('100'); //throws

```

**Comment by silfverstrom** [comment]
The documentation has been updated to illuminate this syntax.
