### ISSUE TITLE
Add an all/any type

### ISSUE THREAD

**Issue by br0r** [silfverstrom/duns.js#9]
Sometimes it doesn't really matter what type a variable is, it simple needs to exist.
Therefore there should exist some kind of "all catcher" type.

```
Duns.validate(['5', 5], Duns.array().items([
  Duns.any().disallow('4')
]));
```

**Comment by silfverstrom** [comment]
Yes i agree - this is an important addition.
0.1?

**Comment by br0r** [comment]
As as response to the Pull Request, shouldn't all validators be an extension of the any validator? Using es6 `class extend` this could be done quite easy.

**Comment by silfverstrom** [comment]
Yes I agree. I thought about it in the end when I realised there was quite some duplicates. My thought was to get the functionality in place, and then do some cleanup in 0.2 release when all 0.1 functionality is done.

**Comment by br0r** [comment]
All right! I'll close this issue and open a new with 0.2 milestone.
